/**
 * Stable English names for established HOI4 country tags.
 *
 * This is intentionally an open string lookup rather than a closed enum:
 * dynamic, cosmetic and modded tags remain valid and fall back to their exact
 * raw value. Campaign-specific cosmetic names are not inferred here.
 */
export const COUNTRY_DISPLAY_NAMES: Readonly<Record<string, string>> =
  Object.freeze({
    AFA: "Afar",
    AFG: "Afghanistan",
    ALB: "Albania",
    ALG: "Algeria",
    ANG: "Angola",
    ARG: "Argentina",
    ARM: "Armenia",
    AST: "Australia",
    AUS: "Austria",
    AZR: "Azerbaijan",
    BAH: "The Bahamas",
    BAN: "Bangladesh",
    BEL: "Belgium",
    BHU: "Bhutan",
    BLR: "Belarus",
    BLZ: "Belize",
    BOL: "Bolivia",
    BOT: "Botswana",
    BRA: "Brazil",
    BRD: "Burundi",
    BRM: "Burma",
    BUL: "Bulgaria",
    CAM: "Cambodia",
    CAN: "Canada",
    CAR: "Central African Republic",
    CHA: "Chad",
    CHI: "China",
    CHL: "Chile",
    CMR: "Cameroon",
    COG: "Congo",
    COL: "Colombia",
    COS: "Costa Rica",
    CRC: "Curaçao",
    CRO: "Croatia",
    CSA: "Confederate States",
    CUB: "Cuba",
    CYP: "Cyprus",
    CZE: "Czechoslovakia",
    DAH: "Dahomey",
    DDR: "East Germany",
    DEN: "Denmark",
    DJI: "Djibouti",
    DNK: "Denmark",
    DNZ: "Danzig",
    DOM: "Dominican Republic",
    ECU: "Ecuador",
    EGY: "Egypt",
    ELS: "El Salvador",
    ENG: "United Kingdom",
    EQG: "Equatorial Guinea",
    ERI: "Eritrea",
    EST: "Estonia",
    ETH: "Ethiopia",
    FIJ: "Fiji",
    FIN: "Finland",
    FRA: "France",
    FSM: "Micronesia",
    GAB: "Gabon",
    GAM: "The Gambia",
    GDL: "Guadeloupe",
    GEO: "Georgia",
    GER: "Germany",
    GHA: "Ghana",
    GNA: "Guinea",
    GNB: "Guinea-Bissau",
    GRE: "Greece",
    GRN: "Greenland",
    GUA: "Guatemala",
    GUM: "Guam",
    GXC: "Guangxi Clique",
    GYA: "Guyana",
    HAI: "Haiti",
    HAW: "Hawaii",
    HOL: "Netherlands",
    HON: "Honduras",
    HUN: "Hungary",
    ICE: "Iceland",
    INS: "Indonesia",
    IRE: "Ireland",
    IRQ: "Iraq",
    ISR: "Israel",
    ITA: "Italy",
    IVO: "Ivory Coast",
    JAM: "Jamaica",
    JAP: "Japan",
    JOR: "Jordan",
    JPN: "Japan",
    KAZ: "Kazakhstan",
    KEN: "Kenya",
    KOR: "Korea",
    KUW: "Kuwait",
    KYR: "Kyrgyzstan",
    LAO: "Laos",
    LAT: "Latvia",
    LBA: "Libya",
    LEB: "Lebanon",
    LIB: "Liberia",
    LIT: "Lithuania",
    LUX: "Luxembourg",
    MAD: "Madagascar",
    MAL: "Malaysia",
    MAN: "Manchukuo",
    MEN: "Mengkukuo",
    MEX: "Mexico",
    MLD: "Maldives",
    MLI: "Mali",
    MLT: "Malta",
    MNT: "Montenegro",
    MOL: "Moldova",
    MON: "Mongolia",
    MOR: "Morocco",
    MRT: "Mauritania",
    MZB: "Mozambique",
    NAM: "Namibia",
    NEP: "Nepal",
    NED: "Netherlands",
    NGA: "Nigeria",
    NGR: "Niger",
    NIC: "Nicaragua",
    NIR: "Northern Ireland",
    NMB: "Namibia",
    NOR: "Norway",
    NZL: "New Zealand",
    OMA: "Oman",
    PAK: "Pakistan",
    PAL: "Palestine",
    PAN: "Panama",
    PAR: "Paraguay",
    PER: "Iran",
    PHI: "Philippines",
    PNG: "Papua New Guinea",
    POL: "Poland",
    POR: "Portugal",
    PRC: "Communist China",
    PRU: "Peru",
    PUE: "Puerto Rico",
    QAT: "Qatar",
    RAJ: "British Raj",
    RCG: "Republic of the Congo",
    ROM: "Romania",
    ROU: "Romania",
    RUS: "Russia",
    RUT: "Carpathian Ruthenia",
    RWA: "Rwanda",
    SAF: "South Africa",
    SAM: "Samoa",
    SAU: "Saudi Arabia",
    SCO: "Scotland",
    SEN: "Senegal",
    SER: "Serbia",
    SHX: "Shanxi",
    SIA: "Siam",
    SIC: "Shanxi",
    SIE: "Sierra Leone",
    SIK: "Sinkiang",
    SLO: "Slovakia",
    SND: "Sindh",
    SOL: "Solomon Islands",
    SOM: "Somalia",
    SOV: "Soviet Union",
    SPA: "Spain",
    SPR: "Spain",
    SRL: "Sri Lanka",
    SUD: "Sudan",
    SUR: "Suriname",
    SWE: "Sweden",
    SWI: "Switzerland",
    SYR: "Syria",
    TAH: "Tahiti",
    TAJ: "Tajikistan",
    TAN: "Tannu Tuva",
    TIB: "Tibet",
    TMS: "Turkmenistan",
    TOG: "Togo",
    TRI: "Trinidad and Tobago",
    TUN: "Tunisia",
    TUR: "Turkey",
    TZN: "Tanzania",
    UAE: "United Arab Emirates",
    UGA: "Uganda",
    UKR: "Ukraine",
    URG: "Uruguay",
    USA: "United States",
    UZB: "Uzbekistan",
    VEN: "Venezuela",
    VIN: "Vietnam",
    WGR: "West Germany",
    WLS: "Wales",
    XIC: "Xibei San Ma",
    XSM: "Xibei San Ma",
    YEM: "Yemen",
    YUG: "Yugoslavia",
    YUN: "Yunnan",
    ZAM: "Zambia",
    ZIM: "Zimbabwe",
  });

export function getCountryDisplayName(
  tag: string | null | undefined,
): string {
  if (!tag) return "";
  return COUNTRY_DISPLAY_NAMES[tag] ?? tag;
}

export function formatCountryDisplayName(
  tag: string | null | undefined,
  emptyLabel = "—",
): string {
  if (!tag) return emptyLabel;
  const displayName = getCountryDisplayName(tag);
  return displayName === tag ? tag : `${displayName} (${tag})`;
}
