const EQUIPMENT_DISPLAY_NAMES: Readonly<Record<string, string>> = Object.freeze({
  amphibious_mechanized_equipment_1: "Basic Amphibious Tractor",
  amphibious_mechanized_equipment_2: "Improved Amphibious Tractor",
  amphibious_tank_chassis_1: "Amphibious Tank",
  anti_air_equipment_1: "Towed Anti-Aircraft",
  anti_air_equipment_2: "Improved Anti-Air",
  anti_air_equipment_3: "Advanced Anti-Air",
  anti_tank_equipment_1: "Towed Anti-Tank",
  anti_tank_equipment_2: "Improved Anti-Tank",
  anti_tank_equipment_3: "Advanced Anti-Tank",
  armored_car_at_equipment: "Anti-Tank Armored Car",
  armored_car_equipment_1: "Basic Armored Car",
  armored_car_equipment_2: "Improved Armored Car",
  armored_support_vehicle_1: "Armored Support Vehicle",
  artillery_equipment_1: "Towed Artillery",
  artillery_equipment_2: "Improved Artillery",
  artillery_equipment_3: "Advanced Artillery",
  convoy_1: "Convoy",
  cv_small_plane_airframe_0: "Inter-War Carrier Airframe",
  cv_small_plane_airframe_1: "Basic Carrier Airframe",
  cv_small_plane_airframe_2: "Improved Carrier Airframe",
  cv_small_plane_airframe_3: "Advanced Carrier Airframe",
  cv_small_plane_cas_airframe_0: "Inter-War Carrier Close Air Support",
  cv_small_plane_cas_airframe_1: "Basic Carrier Close Air Support",
  cv_small_plane_cas_airframe_2: "Improved Carrier Close Air Support",
  cv_small_plane_cas_airframe_3: "Advanced Carrier Close Air Support",
  cv_small_plane_naval_bomber_airframe_0: "Inter-War Carrier Naval Bomber",
  cv_small_plane_naval_bomber_airframe_2: "Improved Carrier Naval Bomber",
  cv_small_plane_naval_bomber_airframe_3: "Advanced Carrier Naval Bomber",
  floating_harbor_equipment_1: "Floating Harbor",
  gw_armored_car_equipment: "Inter-War Armored Car",
  heavy_tank_chassis_1: "Basic Heavy Tank",
  heavy_tank_chassis_2: "Improved Heavy Tank",
  heavy_tank_chassis_3: "Advanced Heavy Tank",
  heavy_tank_destroyer_chassis_1: "Basic Heavy Tank Destroyer",
  heavy_tank_destroyer_chassis_2: "Improved Heavy Tank Destroyer",
  heavy_tank_destroyer_chassis_3: "Advanced Heavy Tank Destroyer",
  infantry_equipment_0: "Basic Infantry Equipment",
  infantry_equipment_1: "Infantry Equipment I",
  infantry_equipment_2: "Infantry Equipment II",
  infantry_equipment_3: "Infantry Equipment III",
  land_cruiser_chassis_1: "Land Cruiser Chassis",
  large_plane_airframe_0: "Inter-War Large Airframe",
  large_plane_airframe_1: "Basic Large Airframe",
  large_plane_airframe_2: "Improved Large Airframe",
  large_plane_airframe_3: "Advanced Large Airframe",
  large_plane_maritime_patrol_plane_airframe_1:
    "Basic Maritime Patrol Plane",
  large_plane_maritime_patrol_plane_airframe_3:
    "Advanced Maritime Patrol Plane",
  light_tank_aa_chassis_2: "Improved Light SP Anti-Air",
  light_tank_artillery_chassis_2: "Improved Light SP Artillery",
  light_tank_artillery_chassis_3: "Advanced Light SP Artillery",
  light_tank_chassis_0: "Inter-War Light Tank",
  light_tank_chassis_1: "Basic Light Tank",
  light_tank_chassis_2: "Improved Light Tank",
  light_tank_chassis_3: "Advanced Light Tank",
  light_tank_destroyer_chassis_1: "Basic Light Tank Destroyer",
  light_tank_flame_chassis_2: "Improved Light Flame Tank",
  light_tank_flame_chassis_3: "Advanced Light Flame Tank",
  mechanized_equipment_1: "Mechanized Equipment I",
  mechanized_equipment_2: "Mechanized Equipment II",
  mechanized_equipment_3: "Mechanized Equipment III",
  medium_plane_airframe_0: "Inter-War Medium Airframe",
  medium_plane_airframe_1: "Basic Medium Airframe",
  medium_plane_airframe_2: "Improved Medium Airframe",
  medium_plane_airframe_3: "Advanced Medium Airframe",
  medium_plane_fighter_airframe_1: "Basic Heavy Fighter",
  medium_plane_fighter_airframe_2: "Improved Heavy Fighter",
  medium_plane_fighter_airframe_3: "Advanced Heavy Fighter",
  medium_plane_scout_plane_airframe_1: "Basic Scout Plane",
  medium_plane_scout_plane_airframe_2: "Improved Scout Plane",
  medium_plane_scout_plane_airframe_3: "Advanced Scout Plane",
  medium_tank_aa_chassis_2: "Improved Medium SP Anti-Air",
  medium_tank_aa_chassis_3: "Advanced Medium SP Anti-Air",
  medium_tank_artillery_chassis_1: "Basic Medium SP Artillery",
  medium_tank_artillery_chassis_2: "Improved Medium SP Artillery",
  medium_tank_artillery_chassis_3: "Advanced Medium SP Artillery",
  medium_tank_chassis_0: "Inter-War Medium Tank",
  medium_tank_chassis_1: "Basic Medium Tank",
  medium_tank_chassis_2: "Improved Medium Tank",
  medium_tank_chassis_3: "Advanced Medium Tank",
  medium_tank_destroyer_chassis_1: "Basic Medium Tank Destroyer",
  medium_tank_destroyer_chassis_2: "Improved Medium Tank Destroyer",
  medium_tank_destroyer_chassis_3: "Advanced Medium Tank Destroyer",
  medium_tank_flame_chassis_3: "Advanced Medium Flame Tank",
  modern_tank_chassis_1: "Modern Tank",
  mothership_equipment_0: "Mothership Aircraft",
  motorized_equipment_0: "Early Truck",
  motorized_equipment_1: "Truck",
  rocket_artillery_equipment_1: "Towed Rocket Artillery",
  rocket_artillery_equipment_2: "Advanced Rocket Artillery",
  self_propelled_super_heavy_artillery_equipment_1:
    "Self-Propelled Super-Heavy Howitzer",
  small_plane_airframe_0: "Inter-War Small Airframe",
  small_plane_airframe_1: "Basic Small Airframe",
  small_plane_airframe_2: "Improved Small Airframe",
  small_plane_airframe_3: "Advanced Small Airframe",
  small_plane_cas_airframe_0: "Inter-War Close Air Support",
  small_plane_cas_airframe_1: "Basic Close Air Support",
  small_plane_cas_airframe_2: "Improved Close Air Support",
  small_plane_cas_airframe_3: "Advanced Close Air Support",
  small_plane_naval_bomber_airframe_0: "Inter-War Naval Bomber",
  small_plane_naval_bomber_airframe_1: "Basic Naval Bomber",
  small_plane_naval_bomber_airframe_2: "Improved Naval Bomber",
  small_plane_naval_bomber_airframe_3: "Advanced Naval Bomber",
  strat_bomber_intercontinental_equipment_1: "Intercontinental Bomber",
  super_heavy_artillery_equipment_1: "Super-Heavy Howitzer",
  support_equipment_1: "Support Equipment",
  train_equipment_1: "Civilian Train",
  train_equipment_2: "War Austerity Train",
  train_equipment_3: "Armored Train",
  transport_plane_equipment_1: "Inter-War Transport Plane",
  transport_plane_equipment_2: "Improved Transport Plane",
  transport_plane_equipment_3: "Modern Transport Plane",
});

export function formatEquipmentDefinition(definition: string): string {
  const knownName = EQUIPMENT_DISPLAY_NAMES[definition.trim().toLowerCase()];
  if (knownName) return knownName;
  const readable = definition.trim().replace(/_+/g, " ");
  if (!readable) return definition;
  return readable.charAt(0).toUpperCase() + readable.slice(1);
}
